### ISSUE TITLE
Check Network State 

### ISSUE THREAD

**Issue by arky** [AfricaHackTrip/simple-speed#22]
When the user taps [Start Test] check if the network state if offline or online. 

Tested on FIrefox Android Nightly on Samsung S2  CM10.3

**Comment by raucao** [comment]
... and don't start the test if detected as offline? Maybe show a warning?

**Comment by arky** [comment]
Show a warning would be ideal.

**Comment by raucao** [comment]
Ok, will implement this using `navigator.onLine`. Thanks!

**Comment by arky** [comment]
Awesome Thanks @skddc!

**Comment by raucao** [comment]
Ok, unfortunately we can't do this yet, due to browser support not being good enough. It works on Chrome and Safari for me (OS X), but Firefox just keeps stating it's online, even when I disable the wi-fi.

There's a bug report already: https://bugzilla.mozilla.org/show_bug.cgi?id=783516

I added myself to the CC list. Please also vote for it!

**Comment by arky** [comment]
That's interesting @skddc 

The navigator.online demo runs properly on my Mozilla Firefox nightly (nightly.mozilla.org) as expected. 
http://html5-demos.appspot.com/static/navigator.onLine.html

What the bug #783516 needs is a good test case.

**Comment by raucao** [comment]
> Platform: All Mac OS X

;)

**Comment by raucao** [comment]
Oh crap, this is intended behaviour: https://bugzilla.mozilla.org/show_bug.cgi?id=620472

I disagree with the winning argument of the discussion, but apparently it's been had and the decision was made. I'll implement it after all then, because some Firefox for Mac users not seeing the message is not a show stopper.

**Comment by raucao** [comment]
Ok, done.

By the way, @arky, wanna [rate the app](https://marketplace.firefox.com/app/simple-speed/)?
